application: lk-consulting
version: 1
runtime: php
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /img
  #static_files: /img/.*\.(gif|png|jpg)
  #upload: img/.*\.(gif|png|jpg)$
  static_dir: img

- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

- url: /(.+\.php)$ 
  script: \1

- url: /style
  mime_type: text/css
  static_dir: style

- url: /scripts
  #static_files: \1
  #upload: \1.js
  static_dir: scripts

- url: /*
  script: main.php

